import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBarLeft from '@/components/SideBarLeft/SideBarLeft';
import Header from '@/components/Main/Header/Header';
import { getDirectoryTree } from '@/utils/directory';
import path from 'path';
import styles from './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const postTree = getDirectoryTree(path.join(process.cwd(), 'posts'));

  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/cf485cac6a.js" crossOrigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <div className="container">
          <SideBarLeft postTree={postTree} />
          <div className={styles.main}>
        <Header />
        <div className = {styles.page}>
            {children}
        </div>
        
    </div> 
        </div>
      </body>
    </html>
  );
}